### PR TITLE
Always log version when running command

### PR DESCRIPTION
**Pull request by kajes**
Added a log entry with useful debug information that is logged on every command run.

Fixes SA-20133

### CODE REVIEW

**Comment by danijeel** [comment]
Based on the feedback I've seen, I think it would be useful to display the current version of sdpctl  to stdout when running `sdpctl appliance upgrade prepare` and `sdpctl appliance upgrade complete`

**Comment by kajes** [comment]
> Based on the feedback I've seen, I think it would be useful to display the current version of sdpctl to **stdout** when running `sdpctl appliance upgrade prepare` and `sdpctl appliance upgrade complete`

In that case, we might as well print that for every command. I'm guessing that if we only print it for those two, there will definitely be requests for printing it for the others as well.

**Comment by danijeel** [comment]
>In that case, we might as well print that for every command. I'm guessing that if we only print it for those two, there will definitely be requests for printing it for the others as well.

no this will be a very bad change, this will hinder the usage of sdpctl in conjunction with other projects with pipes.

**Comment by kajes** [comment]
Should be better now.

**Review by danijeel — APPROVED** [review]

**Pull request merged**
